version: "3.7"

volumes:
  database:
  packages:
  extensions:

networks:
  proget:

services:
  proget:
    image: phoenixtzuyun/proget:5.3.4
    restart: always
    environment:
      - PROGET_DB_TYPE=SqlServer
      - "PROGET_DATABASE=Data Source=proget-sql;Initial Catalog=ProGet;User ID=sa;Password=aa123456"
    volumes:
      - packages:/var/proget/packages
      - extensions:/var/proget/extensions
    ports:
      - 80:80
    networks:
      - proget
    depends_on:
      - proget-sql
    # healthcheck:
    #   test: curl --write-out %{http_code} -s --output /dev/null localhost | grep 200 || exit 1
    #   interval: 5s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s

  proget-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=aa123456
    restart: unless-stopped
    networks:
      - proget
    ports:
      - 1433:1433
